(test
 (name parser_test)
 (modules parser_test)
 (libraries casbin))
(test
 (name expr_test)
 (modules expr_test)
 (libraries casbin))
(test
 (name enforcer_test)
 (modules enforcer_test)
 (libraries casbin))
(test
 (name effect_test)
 (modules effect_test)
 (libraries casbin))
(test
 (name management_test)
 (modules management_test)
 (libraries casbin))
(test
 (name key_match_test)
 (modules key_match_test)
 (libraries casbin))
(test
 (name domain_test)
 (modules domain_test)
 (libraries casbin))
(test
 (name abac_test)
 (modules abac_test)
 (libraries casbin))
